name: .NET Framework 4.8

on:
  push:
    branches: [ "master" ]
    tags:
      - '*'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build
        run: msbuild /p:Configuration=Release

      - name: Publish
        run: msbuild /p:Configuration=Release /t:Publish


      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bin
          path: BadExe/

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: BadExe/bin/Release/BadExe.exe
